### ISSUE TITLE
not sure if it's a good practice to show his pass in github

### ISSUE THREAD

**Issue by flyingrub** [N07070/n07070-tk-V3#7]
https://github.com/N07070/n07070-tk-V3/blob/master/model/php/admin.php#L8

**Comment by N07070** [comment]
This should be in a file. Agreed. Will fix ASAP ( or submit a PR ). Thanks for the report !

•

**Comment by N07070** [comment]
Fixed 7e54d80d812f081abadde82b0a701de70265d6d7
